### ISSUE TITLE
Noch eine Anmerkung

### ISSUE THREAD

**Issue by veraniedermayer** [Hammer-und-Partner/Website#7]
Bitte hinter alle Stellen Folgendes ergänzen: (m/w/d)

Das heißt, dass männlich, weiblich, diverse Mitarbeiter gesucht werden.

**Comment by MoinJulian** [comment]
@veraniedermayer das steht doch bereits dahinter: https://hammer.partners/karriere/job/8-wirtschaftspruefer

**Comment by veraniedermayer** [comment]
***@***.***


Mit freundlichen Grüßen

Veruschka Niedermayer
Leitung Personal & Organisation
Betriebswirtin (VWA)



Hammer & Partner mbB

Wirtschaftsprüfer | Steuerberater | Rechtsanwälte

Außer der Schleifmühle 75
28203 Bremen

T       +49 421 36 904 67
E       ***@***.******@***.***>

hammer.partners<https://hammer.partners/>



Vertraulichkeitshinweis: Diese Nachricht und jeder übermittelte Anhang beinhaltet vertrauliche Informationen und ist nur für die Personen oder das Unternehmen bestimmt, an welches sie tatsächlich gerichtet ist. Sollte diese E-Mail nicht für Sie bestimmt sein, weisen wir Sie darauf hin, dass die Verbreitung, das (auch teilweise) Kopieren sowie der Gebrauch der empfangenen E-Mail und der darin enthaltenen Informationen gesetzlich verboten ist und gegebenenfalls Schadensersatzpflichten auslösen kann. Sollten Sie diese Nachricht aufgrund eines Übermittlungsfehlers erhalten haben, bitten wir Sie, den Absender unverzüglich hiervon in Kenntnis zu setzen. Sicherheitswarnung: Bitte beachten Sie, dass das Internet kein sicheres Kommunikationsmedium ist. Obwohl wir im Rahmen unseres Qualitätsmanagements unter Beachtung und der gebotenen Sorgfalt Maßnahmen ergriffen haben, um einen Computervirenbefall weitestgehend zu verhindern, können wir wegen der Natur des Internets das Risiko eines Computervirenbefalls dieser E-Mail nicht ausschließen.
Angaben gem.§ 37a HGB resp. § 35a GmbHG Hammer & Partner mbB Wirtschaftsprüfer, Steuerberater und Rechtsanwälte - Partnerschaftsgesellschaft mit beschränkter Berufshaftung. Partner: Thorsten Hammer (WP, StB), Karsten Brahms (WP, StB), Marc-Andreas Hustedt (StB), Corinna Hammer (StB), Petra Kriesten (StB). Sitz der Gesellschaft: Bremen Eingetragen im Partnerschaftsregister des Amtsgericht Bremen unter PR 128 UST-IDNR: DE 114526801
In Kooperation mit Hammer & Brahms GmbH Wirtschaftsprüfungsgesellschaft, Geschäftsführer: Thorsten Hammer, Karsten Brahms, Corinna Hammer, Sitz der Gesellschaft: Bremen Eingetragen im Handelsregister des Amtsgerichts Bremen unter HRB 22168 UST-IDNR: DE 235699079 und mit Hammer partners Rechtsanwaltsgesellschaft mbH, Geschäftsführer: Marc-Andreas Hustedt, Felix Westpfahl, Sitz der Gesellschaft: Bremen eingetragen im Handelsregister des Amtsgerichts Bremen unter HRB 37547 UST-IDNR: DE 349144132
Zu den Informationen gemäß den Artikeln 13 und 14 und allen Mitteilungen gemäß den Artikeln 15 bis 22 und Artikel 34 der Datenschutz-Grundverordnung, verweisen wir auf unsere Website https://hammer.partners.
Von: Julian Hammer ***@***.***>
Gesendet: Montag, 23. September 2024 13:19
An: Hammer-partners-IT-GmbH/Website ***@***.***>
Cc: Niedermayer, Veruschka ***@***.***>; Mention ***@***.***>
Betreff: Re: [Hammer-partners-IT-GmbH/Website] Noch eine Anmerkung (Issue #7)


@veraniedermayer<https://github.com/veraniedermayer> das steht doch bereits dahinter: https://hammer.partners/karriere/job/8-wirtschaftspruefer

**Comment by MoinJulian** [comment]
Also hier?

![image](https://github.com/user-attachments/assets/c74a4d4e-493e-4bcf-8a73-037a29ef0df7)
